language: node_js
node_js:
  - node
  - lts/*
script:
  - yarn build
  - yarn test -- --coverage --coverageReporters lcov
after_success:
  - cat ./coverage/lcov.info | coveralls
before_deploy:
  - rm -rf lib
  - NODE_ENV=production yarn build
deploy:
  provider: npm
  email: dev.ukatama@gmail.com
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_NODE_VERSION = lts/*
  api_key: $NPM_AUTH_TOKEN
